// <auto-generated />
using System;
using MatrizPerfiles.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatrizPerfiles.Web.Migrations
{
    [DbContext(typeof(MatrizPerfilesContext))]
    partial class MatrizPerfilesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatrizPerfiles.Web.Models.PbiMatrizPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoDePrograma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bloque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carpeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoIdFuncion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionUnidadOrganizativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FuenteDeDatos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionNivel7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionRolAsociado")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionDeMenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int?>("SistemaId")
                        .HasColumnType("int");

                    b.Property<string>("Sitio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubModulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSitio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDePerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vistas")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Workflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workview")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("IX_PbiMatrizPerfil_Codigo");

                    b.HasIndex("FuncionRolAsociado")
                        .HasDatabaseName("IX_PbiMatrizPerfil_FuncionRolAsociado");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SistemaId")
                        .HasDatabaseName("IX_PbiMatrizPerfil_SistemaId");

                    b.HasIndex("Vistas")
                        .HasDatabaseName("IX_PbiMatrizPerfil_Vistas");

                    b.ToTable("PbiMatrizPerfiles", (string)null);
                });

            modelBuilder.Entity("MatrizPerfiles.Web.Models.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Puestos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Analista de Crédito"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gerente de Sucursal"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cajero"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Auditor Interno"
                        });
                });

            modelBuilder.Entity("MatrizPerfiles.Web.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sistemas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sistema Core"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CRM"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ERP Financiero"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Banca Móvil"
                        });
                });

            modelBuilder.Entity("MatrizPerfiles.Web.Models.PbiMatrizPerfil", b =>
                {
                    b.HasOne("MatrizPerfiles.Web.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MatrizPerfiles.Web.Models.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Puesto");

                    b.Navigation("Sistema");
                });
#pragma warning restore 612, 618
        }
    }
}
